<?php

namespace App\Console\Commands;

use App\Models\Modules\WNS\PurchaseRequest;
use Illuminate\Console\Command;
use Spatie\Browsershot\Browsershot;

class TestBrowsershotPdf extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:browsershot-pdf {--id=2}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Test Browsershot PDF generation with Purchase Request';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $id = $this->option('id');

        $this->info('Testing Browsershot PDF generation...');

        try {
            // Test basic Browsershot functionality
            $this->info('1. Testing basic Browsershot...');

            $html = '<html><body><h1>Test PDF</h1><p>This is a test PDF generated by Browsershot.</p></body></html>';

            $pdf = Browsershot::html($html)
                ->format('A4')
                ->pdf();

            file_put_contents(storage_path('test-browsershot-basic.pdf'), $pdf);
            $this->info('✓ Basic test PDF saved to: '.storage_path('test-browsershot-basic.pdf'));

            // Test Purchase Request URL
            $this->info('2. Testing Purchase Request URL...');

            $purchaseRequest = PurchaseRequest::find($id);
            if (! $purchaseRequest) {
                $this->error("Purchase Request with ID {$id} not found");

                return 1;
            }

            $url = route('purchase-requests.pdf', $purchaseRequest);
            $this->info("URL: {$url}");

            $pdf = Browsershot::url($url)
                ->format('A4')
                ->landscape()
                ->margins(10, 10, 10, 10)
                ->waitUntilNetworkIdle()
                ->timeout(60)
                ->pdf();

            $filename = storage_path('test-browsershot-pr-'.$purchaseRequest->id.'.pdf');
            file_put_contents($filename, $pdf);
            $this->info("✓ Purchase Request PDF saved to: {$filename}");

            $this->info('Browsershot test completed successfully!');

            return 0;

        } catch (\Exception $e) {
            $this->error('Browsershot test failed: '.$e->getMessage());
            $this->error('Stack trace: '.$e->getTraceAsString());

            return 1;
        }
    }
}
