<?php

namespace Database\Seeders\WNS;

use App\Models\Core\BusinessUnit;
use App\Models\Core\Department;
use App\Models\Core\Position;
use Illuminate\Database\Seeder;

/**
 * Seed WNS / Executive Office department + Chief of Staff position.
 *
 * Context: PRD docs/specs/2026-05-25-wns-restructure-prd.
 *
 * Decision (PO 2026-05-26 revision): Adiel Priyarama is Chief of Staff
 * at WNS (right hand of CEO Fadli, executive-level visibility into all
 * WNS data). He is NOT placed at WG/EXEC. CEO Fadli and MD Bagus remain
 * the only members of WG/EXEC.
 *
 * This seeder creates an EXEC root department under BU=WNS that mirrors
 * the WG/EXEC pattern, with a single COS_EXEC position. The user move is
 * driven separately by wns:migrate-restructure-2026 via WnsRestructure2026Mapping.
 *
 * Idempotent on (business_unit_id, code) for the dept and (department_id,
 * code) for positions.
 *
 * The default 4 positions (EXEC_EXEC/HOD_EXEC/LEAD_EXEC/STAFF_EXEC) are
 * auto-generated by Department::ensureDefaultPositions(); the custom role
 * below sits alongside them without conflict.
 */
class WNSExecutiveOfficeSeeder extends Seeder
{
    public function run(): void
    {
        $wns = BusinessUnit::where('code', 'WNS')->first();

        if (! $wns) {
            $this->command->error('Business Unit WNS not found. Run BusinessUnitSeeder first.');

            return;
        }

        $exec = Department::updateOrCreate(
            [
                'business_unit_id' => $wns->id,
                'code' => 'EXEC',
            ],
            [
                'parent_department_id' => null,
                'name' => 'Executive Office',
                'is_active' => true,
            ]
        );

        $this->command->info("Department seeded: WNS / {$exec->code} (id={$exec->id})");

        foreach ($this->positions() as $position) {
            Position::firstOrCreate(
                [
                    'department_id' => $exec->id,
                    'code' => $position['code'],
                ],
                [
                    'name' => $position['name'],
                    'level' => $position['level'],
                    'access_level' => $position['access_level'],
                    'hierarchy_level' => $position['hierarchy_level'],
                    'is_active' => true,
                ]
            );
        }

        $this->command->info('WNS/EXEC custom positions seeded: '.count($this->positions()).' role(s).');
    }

    /**
     * Custom positions for the WNS Executive Office.
     *
     * Chief of Staff is c_level / executive (hierarchy_level=0). This
     * grants Adiel `Position::scopeTopManagement()` true so he can see
     * all WNS data via the existing executive-scope guards (Activity,
     * Purchasing, IT Support, etc.).
     *
     * @return array<int, array<string, mixed>>
     */
    protected function positions(): array
    {
        return [
            [
                'code' => 'COS_EXEC',
                'name' => 'Chief of Staff',
                'level' => 'c_level',
                'access_level' => 'executive',
                'hierarchy_level' => 0,
            ],
        ];
    }
}
