<?php

namespace Database\Seeders\WG;

use App\Models\Core\BusinessUnit;
use App\Models\Core\Department;
use App\Models\Core\Position;
use Illuminate\Database\Seeder;

/**
 * Seed WG / Executive Office department + custom Board-of-Director positions.
 *
 * Context: PRD docs/specs/2026-05-25-wns-restructure-prd.
 *
 * Decision (PO 2026-05-25): keep legacy WG departments (CEO, MD, SYSADMIN)
 * active. Add a new EXEC root department to host the Board of Director
 * (CEO, MD). Existing users Fadli and Bagus are moved into EXEC by the
 * wns:migrate-restructure-2026 command.
 *
 * Revision (PO 2026-05-26): Adiel is the Chief of Staff at WNS, not at WG.
 * COS_EXEC position has been moved to WNSExecutiveOfficeSeeder under
 * WNS/EXEC. Only CEO_EXEC and MD_EXEC remain here.
 *
 * Idempotent on (business_unit_id, code) for the dept and (department_id,
 * code) for positions.
 *
 * The default 4 positions (EXEC_EXEC/HOD_EXEC/LEAD_EXEC/STAFF_EXEC) are
 * auto-generated by Department::ensureDefaultPositions(); the custom roles
 * below sit alongside them without conflict.
 */
class WGExecutiveOfficeSeeder extends Seeder
{
    public function run(): void
    {
        $wg = BusinessUnit::where('code', 'WG')->first();

        if (! $wg) {
            $this->command->error('Business Unit WG not found. Run BusinessUnitSeeder first.');

            return;
        }

        $exec = Department::updateOrCreate(
            [
                'business_unit_id' => $wg->id,
                'code' => 'EXEC',
            ],
            [
                'parent_department_id' => null,
                'name' => 'Executive Office',
                'is_active' => true,
            ]
        );

        $this->command->info("Department seeded: WG / {$exec->code} (id={$exec->id})");

        foreach ($this->positions() as $position) {
            Position::firstOrCreate(
                [
                    'department_id' => $exec->id,
                    'code' => $position['code'],
                ],
                [
                    'name' => $position['name'],
                    'level' => $position['level'],
                    'access_level' => $position['access_level'],
                    'hierarchy_level' => $position['hierarchy_level'],
                    'is_active' => true,
                ]
            );
        }

        $this->command->info('WG/EXEC custom positions seeded: '.count($this->positions()).' role(s).');
    }

    /**
     * Custom positions for the Board of Director.
     *
     * Both are c_level / executive (hierarchy_level=0). The level enum
     * `c_level` is provided by migration 2026_03_02_112732_add_c_level_*.
     *
     * Chief of Staff (COS_EXEC) lives under WNS/EXEC, not here — see
     * WNSExecutiveOfficeSeeder.
     *
     * @return array<int, array<string, mixed>>
     */
    protected function positions(): array
    {
        return [
            [
                'code' => 'CEO_EXEC',
                'name' => 'Chief Executive Officer',
                'level' => 'c_level',
                'access_level' => 'executive',
                'hierarchy_level' => 0,
            ],
            [
                'code' => 'MD_EXEC',
                'name' => 'Managing Director',
                'level' => 'c_level',
                'access_level' => 'executive',
                'hierarchy_level' => 0,
            ],
        ];
    }
}
